# Generated by Django 4.0.2 on 2022-02-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mail', models.EmailField(max_length=100, null=True)),
                ('score', models.IntegerField(editable=False, null=True, verbose_name='score')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
