# Generated by Django 4.0.2 on 2022-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='upload',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='telefon',
            field=models.CharField(max_length=12, null=True, verbose_name='telefon'),
        ),
    ]
