# Generated by Django 4.0.3 on 2022-07-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0002_remove_postcomments_upload_postcomments_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True, verbose_name='Customer Name')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Customer comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
