# Generated by Django 4.0.3 on 2022-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0003_customercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomments',
            name='customer_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Customer Name'),
        ),
    ]
