# Generated by Django 4.0.2 on 2022-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0005_category_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
