# Generated by Django 4.0.2 on 2022-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0008_customercomments_customer_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mail', models.EmailField(max_length=100, null=True)),
                ('score', models.IntegerField(editable=False, null=True, verbose_name='score')),
                ('telefon', models.CharField(max_length=12, null=True, verbose_name='telefon')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
    ]
