# Generated by Django 4.0.2 on 2022-08-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0009_usermessage_delete_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=300, null=True),
        ),
    ]
