# Generated by Django 4.0.2 on 2022-08-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0010_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.CharField(default='5', max_length=10, null=True),
        ),
    ]
