# Generated by Django 4.0.2 on 2022-08-21 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0012_alter_post_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=250, null=True)),
                ('left_detail', ckeditor.fields.RichTextField(null=True)),
                ('right_1_title', models.CharField(max_length=250, null=True)),
                ('right_1_detail', ckeditor.fields.RichTextField(null=True)),
                ('right_2_title', models.CharField(max_length=250, null=True)),
                ('right_2_detail', ckeditor.fields.RichTextField(null=True)),
                ('right_3_title', models.CharField(max_length=250, null=True)),
                ('right_3_detail', ckeditor.fields.RichTextField(null=True)),
                ('right_4_title', models.CharField(max_length=250, null=True)),
                ('right_4_detail', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
