# Generated by Django 4.0.2 on 2022-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0014_remove_about_right_1_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('OCAK', 'ocak'), ('ŞUBAT', 'subat'), ('MART', 'mart'), ('NİSAN', 'nisan'), ('MAYIS', 'mayis'), ('HAZİRAN', 'haziran'), ('TEMMUZ', 'temmuz'), ('AĞUSTOS', 'agustos'), ('EYLÜL', 'eylül'), ('EKİM', 'ekim'), ('KASIM', 'kasim'), ('ARALIK', 'aralik')], default='NONE', max_length=200),
        ),
    ]
