# Generated by Django 4.0.2 on 2022-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0017_alter_post_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('OCAK', 'OCAK'), ('ŞUBAT', 'ŞUBAT'), ('MART', 'MART'), ('NİSAN', 'NİSAN'), ('MAYIS', 'MAYIS'), ('HAZİRAN', 'HAZİRAN'), ('TEMMUZ', 'TEMMUZ'), ('AĞUSTOS', 'AĞUSTOS'), ('EYLÜL', 'EYLÜL'), ('EKİM', 'EKİM'), ('KASIM', 'KASIM'), ('ARALIK', 'ARALIK')], default='NONE', max_length=200),
        ),
    ]
