# Generated by Django 4.1 on 2023-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0018_alter_post_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('body', models.CharField(max_length=2000, null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('pure_date', models.CharField(default='15.2.2023', editable=False, max_length=200)),
            ],
        ),
    ]
