# Generated by Django 4.1 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0019_duyuru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('body', models.CharField(max_length=2000, null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('date', models.CharField(max_length=10, null=True)),
                ('date_num', models.IntegerField(max_length=10, null=True, verbose_name='YYYYAAGG')),
            ],
        ),
    ]
