# Generated by Django 4.1 on 2023-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0020_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='date_num',
            field=models.IntegerField(null=True, verbose_name='YYYYAAGG'),
        ),
    ]
