# Generated by Django 4.1 on 2023-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0021_alter_instagram_date_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.CharField(choices=[('WEB SITE', 'WEB SITE'), ('DIJITAL TASARIM', 'DIJITAL TASARIM')], max_length=30, null=True),
        ),
    ]
