# Generated by Django 4.1 on 2023-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0022_website_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(choices=[('WEB SITE', 'WEB SITE'), ('DIJITAL TASARIM', 'DIJITAL TASARIM')], default='WEB SITE', max_length=30, null=True),
        ),
    ]
