# Generated by Django 4.1 on 2023-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0023_alter_website_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
