# Generated by Django 4.1 on 2023-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teta', '0024_website_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
